
exports.seed = async (knex, Promise) => {

  await knex('recipes_ingredients').del();


  /*
    { id: 1, name: 'unit' },
    { id: 2, name: 'tsp' },
    { id: 3, name: 'tbs' },
    { id: 4, name: 'oz' },
    { id: 5, name: 'lb' },
    { id: 6, name: 'cup' },
    { id: 7, name: 'pint' },
    { id: 8, name: 'quart' },
    { id: 9, name: 'gallon' }

  */

  return await knex('recipes_ingredients').insert([

    { "id": "1", "recipe_id": "1", "ingredient_id": "5", "amount": "1.00", "unit_of_measurement_id": 6 },
    { "id": "2", "recipe_id": "1", "ingredient_id": "4", "amount": "1.50", "unit_of_measurement_id": 6 },
    { "id": "3", "recipe_id": "1", "ingredient_id": "6", "amount": "1.00", "unit_of_measurement_id": 2 },
    { "id": "4", "recipe_id": "2", "ingredient_id": "3", "amount": "0.50", "unit_of_measurement_id": 6 },
    { "id": "5", "recipe_id": "2", "ingredient_id": "7", "amount": "0.50", "unit_of_measurement_id": 6 },
    { "id": "6", "recipe_id": "2", "ingredient_id": "4", "amount": "0.25", "unit_of_measurement_id": 6 },
    { "id": "7", "recipe_id": "2", "ingredient_id": "8", "amount": "1.00", "unit_of_measurement_id": 2 },
    { "id": "8", "recipe_id": "2", "ingredient_id": "9", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "9", "recipe_id": "2", "ingredient_id": "10", "amount": "1.25", "unit_of_measurement_id": 6 },
    { "id": "10", "recipe_id": "2", "ingredient_id": "11", "amount": "0.50", "unit_of_measurement_id": 2 },
    { "id": "11", "recipe_id": "2", "ingredient_id": "12", "amount": "0.50", "unit_of_measurement_id": 2 },
    { "id": "12", "recipe_id": "2", "ingredient_id": "13", "amount": "6.00", "unit_of_measurement_id": 4 },
    { "id": "13", "recipe_id": "3", "ingredient_id": "14", "amount": "5.00", "unit_of_measurement_id": 1 },
    { "id": "14", "recipe_id": "3", "ingredient_id": "15", "amount": "2.00", "unit_of_measurement_id": 6 },
    { "id": "15", "recipe_id": "3", "ingredient_id": "16", "amount": "0.50", "unit_of_measurement_id": 6 },
    { "id": "16", "recipe_id": "3", "ingredient_id": "17", "amount": "2.00", "unit_of_measurement_id": 3 },
    { "id": "17", "recipe_id": "3", "ingredient_id": "18", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "18", "recipe_id": "3", "ingredient_id": "19", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "19", "recipe_id": "4", "ingredient_id": "20", "amount": "4.00", "unit_of_measurement_id": 6 },
    { "id": "20", "recipe_id": "4", "ingredient_id": "21", "amount": "1.00", "unit_of_measurement_id": 5 },
    { "id": "21", "recipe_id": "4", "ingredient_id": "3", "amount": "3.00", "unit_of_measurement_id": 3 },
    { "id": "22", "recipe_id": "4", "ingredient_id": "22", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "23", "recipe_id": "4", "ingredient_id": "23", "amount": "8.00", "unit_of_measurement_id": 4 },
    { "id": "24", "recipe_id": "4", "ingredient_id": "24", "amount": "1.00", "unit_of_measurement_id": 6 },
    { "id": "25", "recipe_id": "4", "ingredient_id": "25", "amount": "0.50", "unit_of_measurement_id": 6 },
    { "id": "26", "recipe_id": "4", "ingredient_id": "26", "amount": "4.00", "unit_of_measurement_id": 4 },
    { "id": "27", "recipe_id": "4", "ingredient_id": "27", "amount": "4.00", "unit_of_measurement_id": 4 },
    { "id": "28", "recipe_id": "4", "ingredient_id": "28", "amount": "1.00", "unit_of_measurement_id": 6 },
    { "id": "29", "recipe_id": "4", "ingredient_id": "29", "amount": "0.50", "unit_of_measurement_id": 6 },
    { "id": "30", "recipe_id": "4", "ingredient_id": "30", "amount": "0.25", "unit_of_measurement_id": 6 },
    { "id": "31", "recipe_id": "4", "ingredient_id": "31", "amount": "1.00", "unit_of_measurement_id": 2 },
    { "id": "32", "recipe_id": "4", "ingredient_id": "11", "amount": "0.50", "unit_of_measurement_id": 2 },
    { "id": "33", "recipe_id": "4", "ingredient_id": "32", "amount": "0.50", "unit_of_measurement_id": 2 },
    { "id": "34", "recipe_id": "4", "ingredient_id": "33", "amount": "1.00", "unit_of_measurement_id": 5 },
    { "id": "35", "recipe_id": "5", "ingredient_id": "34", "amount": "1.00", "unit_of_measurement_id": 5 },
    { "id": "36", "recipe_id": "5", "ingredient_id": "35", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "37", "recipe_id": "5", "ingredient_id": "36", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "38", "recipe_id": "5", "ingredient_id": "37", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "39", "recipe_id": "5", "ingredient_id": "38", "amount": "4.00", "unit_of_measurement_id": 4 },
    { "id": "40", "recipe_id": "5", "ingredient_id": "39", "amount": "0.50", "unit_of_measurement_id": 6 },
    { "id": "41", "recipe_id": "5", "ingredient_id": "40", "amount": "0.50", "unit_of_measurement_id": 6 },
    { "id": "42", "recipe_id": "6", "ingredient_id": "3", "amount": "2.00", "unit_of_measurement_id": 3 },
    { "id": "43", "recipe_id": "6", "ingredient_id": "22", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "44", "recipe_id": "6", "ingredient_id": "41", "amount": "1.00", "unit_of_measurement_id": 3 },
    { "id": "45", "recipe_id": "6", "ingredient_id": "42", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "46", "recipe_id": "6", "ingredient_id": "43", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "47", "recipe_id": "6", "ingredient_id": "44", "amount": "1.00", "unit_of_measurement_id": 2 },
    { "id": "48", "recipe_id": "6", "ingredient_id": "45", "amount": "0.50", "unit_of_measurement_id": 6 },
    { "id": "49", "recipe_id": "6", "ingredient_id": "33", "amount": "1.00", "unit_of_measurement_id": 5 },
    { "id": "50", "recipe_id": "6", "ingredient_id": "46", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "51", "recipe_id": "6", "ingredient_id": "47", "amount": "8.00", "unit_of_measurement_id": 6 },
    { "id": "52", "recipe_id": "7", "ingredient_id": "48", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "53", "recipe_id": "7", "ingredient_id": "34", "amount": "1.00", "unit_of_measurement_id": 5 },
    { "id": "54", "recipe_id": "7", "ingredient_id": "49", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "55", "recipe_id": "7", "ingredient_id": "50", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "56", "recipe_id": "8", "ingredient_id": "33", "amount": "1.00", "unit_of_measurement_id": 5 },
    { "id": "57", "recipe_id": "8", "ingredient_id": "51", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "58", "recipe_id": "8", "ingredient_id": "52", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "59", "recipe_id": "8", "ingredient_id": "3", "amount": "1.00", "unit_of_measurement_id": 3 },
    { "id": "60", "recipe_id": "9", "ingredient_id": "53", "amount": "1.00", "unit_of_measurement_id": 3 },
    { "id": "61", "recipe_id": "9", "ingredient_id": "54", "amount": "1.00", "unit_of_measurement_id": 5 },
    { "id": "62", "recipe_id": "9", "ingredient_id": "22", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "63", "recipe_id": "9", "ingredient_id": "41", "amount": "2.00", "unit_of_measurement_id": 3 },
    { "id": "64", "recipe_id": "9", "ingredient_id": "55", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "65", "recipe_id": "9", "ingredient_id": "42", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "66", "recipe_id": "9", "ingredient_id": "56", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "67", "recipe_id": "9", "ingredient_id": "57", "amount": "1.00", "unit_of_measurement_id": 3 },
    { "id": "68", "recipe_id": "9", "ingredient_id": "58", "amount": "2.00", "unit_of_measurement_id": 1 },
    { "id": "69", "recipe_id": "9", "ingredient_id": "59", "amount": "3.00", "unit_of_measurement_id": 3 },
    { "id": "70", "recipe_id": "9", "ingredient_id": "60", "amount": "2.00", "unit_of_measurement_id": 2 },
    { "id": "71", "recipe_id": "9", "ingredient_id": "61", "amount": "2.00", "unit_of_measurement_id": 1 },
    { "id": "72", "recipe_id": "9", "ingredient_id": "20", "amount": "2.00", "unit_of_measurement_id": 6 },
    { "id": "73", "recipe_id": "9", "ingredient_id": "62", "amount": "2.00", "unit_of_measurement_id": 1 },
    { "id": "74", "recipe_id": "9", "ingredient_id": "38", "amount": "8.00", "unit_of_measurement_id": 4 },
    { "id": "75", "recipe_id": "9", "ingredient_id": "40", "amount": "0.50", "unit_of_measurement_id": 6 },
    { "id": "76", "recipe_id": "9", "ingredient_id": "18", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "77", "recipe_id": "10", "ingredient_id": "63", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "78", "recipe_id": "10", "ingredient_id": "51", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "79", "recipe_id": "11", "ingredient_id": "64", "amount": "0.50", "unit_of_measurement_id": 6 },
    { "id": "80", "recipe_id": "11", "ingredient_id": "65", "amount": "2.00", "unit_of_measurement_id": 6 },
    { "id": "81", "recipe_id": "11", "ingredient_id": "66", "amount": "0.50", "unit_of_measurement_id": 6 },
    { "id": "82", "recipe_id": "11", "ingredient_id": "67", "amount": "1.00", "unit_of_measurement_id": 6 },
    { "id": "83", "recipe_id": "11", "ingredient_id": "9", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "84", "recipe_id": "11", "ingredient_id": "68", "amount": "2.00", "unit_of_measurement_id": 3 },
    { "id": "85", "recipe_id": "11", "ingredient_id": "69", "amount": "0.25", "unit_of_measurement_id": 6 },
    { "id": "86", "recipe_id": "12", "ingredient_id": "70", "amount": "2.00", "unit_of_measurement_id": 5 },
    { "id": "87", "recipe_id": "12", "ingredient_id": "53", "amount": "0.30", "unit_of_measurement_id": 6 },
    { "id": "88", "recipe_id": "12", "ingredient_id": "41", "amount": "2.00", "unit_of_measurement_id": 3 },
    { "id": "89", "recipe_id": "12", "ingredient_id": "71", "amount": "2.00", "unit_of_measurement_id": 3 },
    { "id": "90", "recipe_id": "12", "ingredient_id": "72", "amount": "0.30", "unit_of_measurement_id": 6 },
    { "id": "91", "recipe_id": "12", "ingredient_id": "73", "amount": "0.25", "unit_of_measurement_id": 6 },
    { "id": "92", "recipe_id": "12", "ingredient_id": "32", "amount": "0.50", "unit_of_measurement_id": 2 },
    { "id": "93", "recipe_id": "12", "ingredient_id": "51", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "94", "recipe_id": "13", "ingredient_id": "29", "amount": "1.00", "unit_of_measurement_id": 6 },
    { "id": "95", "recipe_id": "13", "ingredient_id": "3", "amount": "4.00", "unit_of_measurement_id": 3 },
    { "id": "96", "recipe_id": "13", "ingredient_id": "22", "amount": "0.50", "unit_of_measurement_id": 1 },
    { "id": "97", "recipe_id": "13", "ingredient_id": "41", "amount": "2.00", "unit_of_measurement_id": 3 },
    { "id": "98", "recipe_id": "13", "ingredient_id": "11", "amount": "2.00", "unit_of_measurement_id": 2 },
    { "id": "99", "recipe_id": "13", "ingredient_id": "32", "amount": "0.25", "unit_of_measurement_id": 2 },
    { "id": "100", "recipe_id": "13", "ingredient_id": "67", "amount": "0.50", "unit_of_measurement_id": 6 },
    { "id": "101", "recipe_id": "13", "ingredient_id": "74", "amount": "2.00", "unit_of_measurement_id": 2 },
    { "id": "102", "recipe_id": "13", "ingredient_id": "34", "amount": "0.75", "unit_of_measurement_id": 5 },
    { "id": "103", "recipe_id": "13", "ingredient_id": "75", "amount": "0.50", "unit_of_measurement_id": 5 },
    { "id": "104", "recipe_id": "13", "ingredient_id": "9", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "105", "recipe_id": "13", "ingredient_id": "76", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "106", "recipe_id": "13", "ingredient_id": "10", "amount": "2.00", "unit_of_measurement_id": 3 },
    { "id": "107", "recipe_id": "13", "ingredient_id": "77", "amount": "1.50", "unit_of_measurement_id": 6 },
    { "id": "108", "recipe_id": "13", "ingredient_id": "25", "amount": "0.25", "unit_of_measurement_id": 6 },
    { "id": "109", "recipe_id": "13", "ingredient_id": "78", "amount": "2.00", "unit_of_measurement_id": 3 },
    { "id": "110", "recipe_id": "14", "ingredient_id": "79", "amount": "4.00", "unit_of_measurement_id": 1 },
    { "id": "111", "recipe_id": "14", "ingredient_id": "3", "amount": "4.00", "unit_of_measurement_id": 3 },
    { "id": "112", "recipe_id": "14", "ingredient_id": "67", "amount": "0.50", "unit_of_measurement_id": 6 },
    { "id": "113", "recipe_id": "15", "ingredient_id": "22", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "114", "recipe_id": "15", "ingredient_id": "80", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "115", "recipe_id": "15", "ingredient_id": "81", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "116", "recipe_id": "15", "ingredient_id": "78", "amount": "1.00", "unit_of_measurement_id": 3 },
    { "id": "117", "recipe_id": "15", "ingredient_id": "82", "amount": "1.00", "unit_of_measurement_id": 2 },
    { "id": "118", "recipe_id": "15", "ingredient_id": "32", "amount": "1.00", "unit_of_measurement_id": 2 },
    { "id": "119", "recipe_id": "15", "ingredient_id": "33", "amount": "1.00", "unit_of_measurement_id": 5 },
    { "id": "120", "recipe_id": "15", "ingredient_id": "20", "amount": "2.00", "unit_of_measurement_id": 6 },
    { "id": "121", "recipe_id": "15", "ingredient_id": "83", "amount": "1.00", "unit_of_measurement_id": 1 },
    { "id": "122", "recipe_id": "15", "ingredient_id": "84", "amount": "1.00", "unit_of_measurement_id": 1 }

  ]);

  // return await knex.raw('SELECT setval(\'recipes_ingredients_id_seq\', (SELECT MAX(id) from recipes_ingredients));'); // postgres

};
